# Generated by Django 4.0.1 on 2022-01-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='state',
        ),
    ]
