# Generated by Django 4.0.1 on 2022-01-21 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='vaccine_card',
            new_name='strategy_id',
        ),
    ]
